export const AUDIO_CAPTURE_CONFIG = {
  SAMPLE_RATE: 16000,
  BUFFER_SIZE: 512,

  VAD_POSITIVE_SPEECH_THRESHOLD: 0.5,
  VAD_NEGATIVE_SPEECH_THRESHOLD: 0.35,
  VAD_MIN_SPEECH_FRAMES: 3,
  VAD_PRE_SPEECH_PAD_FRAMES: 10,
  VAD_REDEMPTION_FRAMES: 10,

  CHUNK_SOFT_LIMIT_MS: 5 * 60 * 1000,
  CHUNK_HARD_LIMIT_MS: 6 * 60 * 1000,
  CHUNK_SOFT_LIMIT_SAMPLES: 5 * 60 * 16000,
  CHUNK_HARD_LIMIT_SAMPLES: 6 * 60 * 16000,
} as const;

export const DICTATION_CONFIG = {
  SEGMENT_COMPLETION_TIMEOUT_MS: 8000,
} as const;

export const WHISPER_CONFIG = {
  BINARY_CHECK_TIMEOUT_MS: 5000,
  TRANSCRIPTION_TIMEOUT_MS: 180000,
} as const;

export const WINDOW_CONFIG = {
  MARGIN_PX: 20,
} as const;
